#!/usr/bin/env python3
"""
New H1 2026 markets to append to the spreadsheet + dashboard, expanding coverage
to nearly all sovereign states (China deliberately excluded).

Each entry:
  country, iso2, region, flag, status, scope, severity(0-100), china_sentiment(0-100),
  china_trigger, assessment_note, source_url, obligations(list)

Scoring conventions (match existing 70-market tab):
- Severity blends REGULATORY BURDEN ON PLATFORMS regardless of motive:
  democratic child-safety/DP burden AND authoritarian censorship burden both raise it.
- China sentiment = HOST govt posture toward Chinese tech: high = hostile/restrictive,
  low = friendly/aligned/BRI-dependent.
- Obligation labels drawn from the 10 canonical labels.
"""

# canonical obligation shorthands
AA = "Age Assurance / Gating"
PC = "Parental Consent"
AR = "Access Restriction"
DR = "Design Restrictions"
DP = "Data Protection"
CM = "Content Moderation"
RA = "Risk Assessment"
TR = "Transparency Reporting"
UE = "User Empowerment / Redress"
AI = "AI Transparency / Content Labelling"

# Region buckets consistent with existing tab
NEW_MARKETS = [
    # ---- Authoritarian / heavy-censorship (high severity, China-aligned => low china sentiment) ----
    ("North Korea", "KP", "Asia Pacific", "🇰🇵", "Enforced",
     "Social Media; Streaming; Direct Messaging", 92, 5,
     "Total dependence on China for external connectivity; Chinese tech is the lifeline",
     "No open internet; domestic intranet (Kwangmyong) only with near-zero foreign platform access. Maximal state control.",
     "https://freedomhouse.org/country/north-korea/freedom-net",
     [AR, CM, DP]),
    ("Iran", "IR", "Middle East", "🇮🇷", "Enforced",
     "Social Media; Streaming; Direct Messaging; AI Service", 88, 8,
     "25-year strategic pact; sanctioned-state reliance on Chinese tech; explicitly emulating China's model",
     "Pervasive filtering plus User Protection Bill / cyberspace regulatory system: IRGC gateway control, ID-to-access, VPN criminalization. National-internet build-out.",
     "https://www.article19.org/resources/iran-user-protection-bill/",
     [AR, CM, DP, RA]),
    ("Russia", "RU", "Europe", "🇷🇺", "Enforced",
     "Social Media; Streaming; Direct Messaging; App Store", 86, 10,
     "Huawei and Chinese infrastructure welcomed as strategic partner; Chinese apps not targeted",
     "Sovereign Internet Law, data-localization (242-FZ), Roskomnadzor blocking. WhatsApp blocked, state Max messenger pushed, mass VPN crackdown.",
     "https://www.roskomsvoboda.org/en/",
     [AR, CM, DP, RA, TR]),
    ("Myanmar", "MM", "Asia Pacific", "🇲🇲", "Enforced",
     "Social Media; Streaming; Direct Messaging", 82, 12,
     "Junta heavily reliant on Chinese backing and surveillance tech",
     "Cybersecurity Law (in force Jul 2025): VPN licensing/ban, local incorporation for large platforms, 3-yr data retention, takedown powers. Frequent shutdowns.",
     "https://www.article19.org/resources/myanmar-cybersecurity-law/",
     [AR, CM, DP, RA]),
    ("Cuba", "CU", "North America", "🇨🇺", "Enforced",
     "Social Media; Direct Messaging", 68, 14,
     "Huawei-built infrastructure; ideological and strategic partner",
     "Decree-Law 370 and Decree-Law 35 criminalize online dissent; state telecom monopoly enables shutdowns during unrest.",
     "https://freedomhouse.org/country/cuba/freedom-net",
     [AR, CM, DP]),
    ("Laos", "LA", "Asia Pacific", "🇱🇦", "Effective",
     "Social Media; Direct Messaging", 60, 12,
     "Deep BRI partner (Laos-China Railway); Chinese digital-infra dependence",
     "Decree on Internet Information Management plus cybercrime laws; national committee reviewing 2026 amendments; new anti-online-fraud center.",
     "https://www.article19.org/resources/laos-internet-decree/",
     [AR, CM, DP]),
    ("Cambodia", "KH", "Asia Pacific", "🇰🇭", "Passed",
     "Social Media; Direct Messaging", 62, 14,
     "Among China's closest regional partners; National Internet Gateway modeled on Chinese architecture",
     "Building China-style National Internet Gateway; cybercrime and cybersecurity law drafts; 2021 data-management sub-decree.",
     "https://stateofsurveillance.org/articles/government/southeast-asia-surveillance-digital-control",
     [AR, CM, DP, RA]),

    # ---- Democratic-backsliding / hybrid ----
    ("Georgia", "GE", "Europe", "🇬🇪", "Enforced",
     "Social Media; Streaming", 66, 40,
     "Strategic partnership with China (2023); Chinese firms in infrastructure; not hostile",
     "Foreign Agents Act (criminal penalties) and 2025 broadcasting amendments expanding content powers, plus an illiberal minors-protection package.",
     "https://www.venice.coe.int/webforms/documents/?country=17&year=all",
     [AR, CM, RA, TR]),
    ("Jordan", "JO", "Middle East", "🇯🇴", "Enforced",
     "Social Media; Direct Messaging", 62, 45,
     "Growing economic and tech ties; not restrictive toward Chinese apps",
     "Cybercrime Law 2023 (broad speech offenses, VPN penalties, platform-manager liability) plus 2023 PDP Law in transition.",
     "https://www.cybertainty.com/jordan-enacts-controversial-cybercrime-legislation/",
     [AR, CM, DP, RA]),
    ("Bangladesh", "BD", "Asia Pacific", "🇧🇩", "Enforced",
     "Social Media; Direct Messaging", 58, 20,
     "Major BRI and infrastructure partner; Chinese tech welcomed",
     "Cyber Security Act 2023 (replaced Digital Security Act) still speech-restrictive; interim government reviewing; Data Protection Act pending.",
     "https://www.article19.org/resources/bangladesh-cyber-security-act/",
     [AR, CM, DP]),

    # ---- Content-control + fraud/scam regulation (moderate-high) ----
    ("Thailand", "TH", "Asia Pacific", "🇹🇭", "Enforced",
     "Social Media; Streaming; Online Marketplace", 64, 30,
     "Major BRI partner; Chinese apps operate freely; scam-crackdown cooperation with China",
     "Computer Crime Act plus PDPA (first fine waves 2024-25) and Emergency Decree on Technology Crimes imposing platform/bank/telecom liability. Heavy URL blocking.",
     "https://www.pdpc.or.th/",
     [AA, DP, CM, RA, TR]),
    ("Nepal", "NP", "Asia Pacific", "🇳🇵", "Effective",
     "Social Media; Direct Messaging", 46, 28,
     "BRI member; TikTok complied and stayed operational while some Western platforms were blocked",
     "2023 Social Media Directive (registration/local contact) enforced Sept 2025; Social Media Bill 2025 withdrawn Feb 2026 after protests; ETA s.47 active.",
     "https://nepallegalfirm.com.np/articles/social-media-regulation-bill-nepal-2025",
     [AR, CM, DP]),

    # ---- Gulf — DP maturing, content-restrictive (moderate) ----
    ("Oman", "OM", "Middle East", "🇴🇲", "Effective",
     "Social Media; Direct Messaging", 54, 32,
     "BRI partner; Chinese tech present, not restricted",
     "PDPL fully enforceable Feb 2026 (GDPR-like) plus Cyber Crime Law covering content and NCII. Regulator MTCIT.",
     "https://www.mtcit.gov.om/",
     [DP, CM, RA]),
    ("Bahrain", "BH", "Middle East", "🇧🇭", "Enforced",
     "Social Media; Direct Messaging", 52, 34,
     "Growing economic ties; not restrictive toward Chinese apps",
     "PDPL (in force 2019), one of the Gulf's earliest, with active regulator plus content controls via press/cyber laws.",
     "https://www.pdp.gov.bh/",
     [DP, CM]),

    # ---- Africa — DP-style regimes, mostly minimal platform-specific rules ----
    ("Ethiopia", "ET", "Africa", "🇪🇹", "Effective",
     "Social Media; Direct Messaging", 50, 15,
     "Huawei/ZTE-built telecom backbone; deep BRI partner",
     "Personal Data Protection Proclamation 1321/2024 in force with strict data localization; Computer Crime Proclamation. Enforcement still ramping.",
     "https://www.inpdp.gov.et/",
     [DP, CM, RA]),
    ("Uganda", "UG", "Africa", "🇺🇬", "Enforced",
     "Social Media; Direct Messaging", 50, 18,
     "Huawei surveillance / Safe City deployments; BRI partner",
     "Data Protection & Privacy Act 2019 (first conviction 2025) plus amended Computer Misuse Act with speech-restrictive provisions.",
     "https://www.pdpo.go.ug/",
     [DP, CM]),
    ("Zimbabwe", "ZW", "Africa", "🇿🇼", "Enforced",
     "Social Media; Direct Messaging", 52, 14,
     "Look East policy; Huawei / Chinese surveillance tech",
     "Cyber & Data Protection Act with 2024 licensing and 2026 aggressive POTRAZ enforcement plus criminal fake-news/cyberbullying provisions.",
     "https://potraz.gov.zw/",
     [DP, CM, RA]),
    ("Tanzania", "TZ", "Africa", "🇹🇿", "Enforced",
     "Social Media; Streaming", 50, 15,
     "Strong BRI partner; has cited China's model approvingly",
     "Personal Data Protection Act 2022 plus Online Content Regulations 2020 that are genuinely restrictive on bloggers and platforms.",
     "https://www.pdpc.go.tz/",
     [DP, CM, TR]),
    ("Rwanda", "RW", "Africa", "🇷🇼", "Enforced",
     "Social Media; Direct Messaging", 46, 18,
     "BRI partner; Chinese infrastructure investment",
     "Law 058/2021 (GDPR-style, extraterritorial, data localization, 48-hr breach notice) enforced by NCSA.",
     "https://dpo.gov.rw/",
     [DP, CM]),
    ("Cameroon", "CM", "Africa", "🇨🇲", "Passed",
     "Social Media; Direct Messaging", 46, 16,
     "Huawei-built infrastructure; BRI partner",
     "New comprehensive DP Law (Dec 2024, strict consent, 18-month grace) plus older cybercrime law; history of regional shutdowns.",
     "https://www.antic.cm/",
     [DP, CM]),
    ("Morocco", "MA", "Africa", "🇲🇦", "Enforced",
     "Social Media; Direct Messaging", 44, 20,
     "First BRI partner in the Maghreb; Huawei/Chinese-infra ties",
     "Law 09-08 on Personal Data Protection (CNDP regulator, one of the region's oldest) plus cybercrime code; no dedicated platform-safety law.",
     "https://www.cndp.ma/",
     [DP, CM]),
    ("Senegal", "SN", "Africa", "🇸🇳", "Enforced",
     "Social Media; Direct Messaging", 44, 16,
     "Major BRI and infrastructure partner",
     "DP Law 2008 (CDP regulator, one of Africa's oldest), reform underway; episodic election-period restrictions.",
     "https://www.cdp.sn/",
     [DP, CM]),
    ("Botswana", "BW", "Africa", "🇧🇼", "Effective",
     "Social Media", 42, 30,
     "Trade ties; not restrictive toward Chinese tech",
     "Data Protection Act 2018 operationalized 2024-25 with a Data Protection Commission; minimal platform-content control.",
     "https://www.bocra.org.bw/",
     [DP]),
    ("Ivory Coast", "CI", "Africa", "🇨🇮", "Effective",
     "Social Media", 40, 18,
     "Growing BRI and infrastructure ties",
     "DP Law 2013 (ARTCI regulator) within the ECOWAS DP framework; minimal platform-specific regulation.",
     "https://www.artci.ci/",
     [DP]),
    ("DR Congo", "CD", "Africa", "🇨🇩", "Proposed",
     "Social Media", 36, 15,
     "Major mining and BRI partner; heavy Chinese presence",
     "Digital Code (2023) includes some data provisions with weak enforcement; episodic shutdowns during unrest.",
     "https://www.arptc.cd/",
     [DP]),
    ("Namibia", "NA", "Africa", "🇳🇦", "Proposed",
     "Social Media", 34, 30,
     "BRI and mining ties; not restrictive",
     "No comprehensive DP law yet; Data Protection Bill in draft. Minimal platform regulation.",
     "https://www.cran.na/",
     [DP]),
    ("Mali", "ML", "Africa", "🇲🇱", "Proposed",
     "Social Media", 34, 20,
     "Warming ties with China amid pivot from Western partners",
     "Limited DP framework; minimal platform-specific regulation; periodic connectivity restrictions.",
     "https://amrtp.ml/",
     [DP]),
    ("Burkina Faso", "BF", "Africa", "🇧🇫", "Proposed",
     "Social Media", 34, 22,
     "Deepening ties with China and non-Western partners",
     "General data-protection baseline; minimal platform-specific regulation; episodic restrictions.",
     "https://www.arcep.bf/",
     [DP]),
    ("Niger", "NE", "Africa", "🇳🇪", "Proposed",
     "Social Media", 32, 22,
     "Pivoting toward non-Western partners including China",
     "Minimal platform-specific regulation; general data-protection provisions only.",
     "https://www.arcep.ne/",
     [DP]),
    ("Chad", "TD", "Africa", "🇹🇩", "Proposed",
     "Social Media", 32, 20,
     "Chinese oil and infrastructure investment",
     "Minimal platform-specific regulation; general data-protection baseline; history of shutdowns.",
     "https://www.arcep.td/",
     [DP]),
    ("Gabon", "GA", "Africa", "🇬🇦", "Proposed",
     "Social Media", 34, 25,
     "Chinese timber and infrastructure ties",
     "Data-protection framework in place (CNPDCP); minimal platform-specific regulation.",
     "https://cnpdcp.ga/",
     [DP]),
    ("Congo", "CG", "Africa", "🇨🇬", "Proposed",
     "Social Media", 32, 20,
     "Chinese infrastructure investment; BRI partner",
     "Limited data-protection framework; minimal platform-specific regulation.",
     "https://www.arpce.cg/",
     [DP]),
    ("Mozambique", "MZ", "Africa", "🇲🇿", "Proposed",
     "Social Media", 34, 18,
     "Major BRI partner; Chinese infrastructure and LNG investment",
     "Emerging data-protection framework; minimal platform-specific regulation.",
     "https://www.incm.gov.mz/",
     [DP]),
    ("Zambia", "ZM", "Africa", "🇿🇲", "Effective",
     "Social Media", 40, 16,
     "Heavy Chinese mining and infrastructure presence; BRI partner",
     "Data Protection Act 2021 plus Cyber Security & Cyber Crimes Act; some content-control provisions.",
     "https://www.zicta.zm/",
     [DP, CM]),
    ("Malawi", "MW", "Africa", "🇲🇼", "Proposed",
     "Social Media", 34, 22,
     "Chinese infrastructure ties; broadly neutral",
     "Data Protection Act 2024 passed; minimal platform-specific regulation.",
     "https://www.macra.mw/",
     [DP]),
    ("Lesotho", "LS", "Africa", "🇱🇸", "Proposed",
     "Social Media", 32, 28,
     "Modest Chinese trade ties",
     "Data Protection Act 2011 with limited enforcement; minimal platform-specific regulation.",
     "https://www.lca.org.ls/",
     [DP]),
    ("Eswatini", "SZ", "Africa", "🇸🇿", "Proposed",
     "Social Media", 30, 55,
     "One of the few Taiwan-recognizing states; limited China ties",
     "Data Protection Act 2022; minimal platform-specific regulation.",
     "https://www.sccom.org.sz/",
     [DP]),
    ("Mauritius", "MU", "Africa", "🇲🇺", "Enforced",
     "Social Media; Online Marketplace", 44, 32,
     "FTA with China; balanced posture",
     "Data Protection Act 2017 (GDPR-aligned, active regulator); ICT Act content provisions.",
     "https://dataprotection.govmu.org/",
     [DP, CM]),
    ("Guinea", "GN", "Africa", "🇬🇳", "Proposed",
     "Social Media", 32, 18,
     "Major bauxite and infrastructure ties with China",
     "Limited data-protection framework; minimal platform-specific regulation; episodic shutdowns.",
     "https://arpt.gov.gn/",
     [DP]),
    ("Sierra Leone", "SL", "Africa", "🇸🇱", "Proposed",
     "Social Media", 30, 25,
     "Chinese infrastructure investment; broadly neutral",
     "Emerging data-protection framework; minimal platform-specific regulation.",
     "https://natcom.gov.sl/",
     [DP]),
    ("Liberia", "LR", "Africa", "🇱🇷", "Proposed",
     "Social Media", 30, 28,
     "Modest Chinese trade and infrastructure ties",
     "Minimal platform-specific regulation; general data-protection provisions only.",
     "https://www.lta.gov.lr/",
     [DP]),
    ("Togo", "TG", "Africa", "🇹🇬", "Effective",
     "Social Media", 38, 20,
     "Chinese infrastructure ties; BRI partner",
     "Data Protection Law 2019 (IPCDP regulator); minimal platform-specific regulation; a 2021 shutdown noted.",
     "https://ipcdp.tg/",
     [DP]),
    ("Benin", "BJ", "Africa", "🇧🇯", "Effective",
     "Social Media", 40, 22,
     "Chinese infrastructure ties; broadly neutral",
     "Digital Code (2017-18) with data-protection provisions (APDP regulator); some restrictive digital-content history.",
     "https://apdp.bj/",
     [DP, CM]),
    ("Mauritania", "MR", "Africa", "🇲🇷", "Proposed",
     "Social Media", 30, 22,
     "Chinese fishing and infrastructure ties",
     "Data Protection Law 2017 with limited enforcement; minimal platform-specific regulation.",
     "https://www.aramtel.mr/",
     [DP]),
    ("Eritrea", "ER", "Africa", "🇪🇷", "Enforced",
     "Social Media; Direct Messaging", 58, 12,
     "Close alignment with China; minimal Western engagement",
     "One of the most restricted information environments; near-total state control of connectivity.",
     "https://freedomhouse.org/country/eritrea/freedom-net",
     [AR, CM]),
    ("Djibouti", "DJ", "Africa", "🇩🇯", "Effective",
     "Social Media", 42, 14,
     "Hosts China's first overseas military base; deep BRI and infrastructure ties",
     "State telecom monopoly; data-protection law 2013; content control during sensitive periods.",
     "https://www.anm.dj/",
     [DP, CM]),
    ("Central African Republic", "CF", "Africa", "🇨🇫", "Proposed",
     "Social Media", 30, 20,
     "Growing Chinese and Russian influence",
     "Minimal platform-specific regulation; nascent data-protection framework.",
     "https://www.art-rca.org/",
     [DP]),
    ("Equatorial Guinea", "GQ", "Africa", "🇬🇶", "Enforced",
     "Social Media; Direct Messaging", 48, 12,
     "Close China alignment; Chinese oil and infrastructure investment",
     "Heavy state control of connectivity with periodic shutdowns; minimal formal platform framework.",
     "https://freedomhouse.org/country/equatorial-guinea",
     [AR, CM]),
    ("Somalia", "SO", "Africa", "🇸🇴", "Proposed",
     "Social Media", 32, 20,
     "Growing Chinese engagement; fragile state",
     "Minimal platform-specific regulation; emerging data-protection discussions; security-driven restrictions.",
     "https://nca.gov.so/",
     [DP]),
    ("Sudan", "SD", "Africa", "🇸🇩", "Enforced",
     "Social Media; Direct Messaging", 54, 18,
     "Chinese investment ties; conflict-driven controls",
     "Conflict-era shutdowns and content controls; Cybercrime Law 2020 speech-restrictive.",
     "https://www.tpra.gov.sd/",
     [AR, CM]),
    ("South Sudan", "SS", "Africa", "🇸🇸", "Proposed",
     "Social Media", 40, 18,
     "Chinese oil investment; broadly aligned",
     "Minimal platform-specific regulation; periodic conflict-driven restrictions.",
     "https://nca.gov.ss/",
     [CM]),
    ("Libya", "LY", "Africa", "🇱🇾", "Proposed",
     "Social Media", 42, 20,
     "Fragmented governance; some Chinese reconstruction interest",
     "Fragmented regulatory environment; periodic connectivity disruptions; no unified platform framework.",
     "https://lptic.ly/",
     [CM]),

    # ---- Central Asia / Caucasus ----
    ("Kyrgyzstan", "KG", "Asia Pacific", "🇰🇬", "Enforced",
     "Social Media; Direct Messaging", 52, 18,
     "BRI partner; heavy Chinese infrastructure and trade ties",
     "2021 'false information' law plus 2023 mass-media law tightening; data-protection framework; content-control powers.",
     "https://digital.gov.kg/",
     [DP, CM, RA]),
    ("Tajikistan", "TJ", "Asia Pacific", "🇹🇯", "Enforced",
     "Social Media; Direct Messaging", 56, 14,
     "Deep BRI partner; heavy Chinese security and infrastructure presence",
     "Extensive filtering and periodic blocking of social platforms; state-controlled connectivity.",
     "https://freedomhouse.org/country/tajikistan/freedom-net",
     [AR, CM]),
    ("Turkmenistan", "TM", "Asia Pacific", "🇹🇲", "Enforced",
     "Social Media; Direct Messaging", 70, 12,
     "Major gas supplier to China; close alignment",
     "One of the world's most restricted internets; most social platforms and VPNs blocked; total state control.",
     "https://freedomhouse.org/country/turkmenistan/freedom-net",
     [AR, CM]),
    ("Armenia", "AM", "Europe", "🇦🇲", "Effective",
     "Social Media", 40, 42,
     "Balanced posture; growing ties with West and neighbors",
     "Data Protection Law 2015 (aligning toward GDPR); minimal platform-specific regulation.",
     "https://foi.am/",
     [DP]),
    ("Mongolia", "MN", "Asia Pacific", "🇲🇳", "Effective",
     "Social Media", 38, 45,
     "Trade-dependent on China but pursues third-neighbor balancing",
     "Personal Data Protection Law (in force 2022) plus Cyber Security Law; minimal platform-content control.",
     "https://itc.gov.mn/",
     [DP]),

    # ---- South & SE Asia remainder ----
    ("Afghanistan", "AF", "Asia Pacific", "🇦🇫", "Enforced",
     "Social Media; Direct Messaging", 66, 25,
     "Taliban engaging China for investment; pragmatic ties",
     "Taliban-era morality-driven content restrictions and periodic platform bans; no formal data-protection regime.",
     "https://freedomhouse.org/country/afghanistan/freedom-net",
     [AR, CM]),
    ("Bhutan", "BT", "Asia Pacific", "🇧🇹", "Effective",
     "Social Media", 38, 40,
     "No formal diplomatic ties with China; cautious posture",
     "Information, Communications & Media Act plus data-protection provisions; minimal platform-specific regulation.",
     "https://www.bicma.gov.bt/",
     [DP]),
    ("Brunei", "BN", "Asia Pacific", "🇧🇳", "Proposed",
     "Social Media", 42, 25,
     "BRI partner; Chinese energy and infrastructure investment",
     "No comprehensive DP law (PDPA in consultation); content governed by Sharia and sedition provisions.",
     "https://www.aiti.gov.bn/",
     [CM]),
    ("Papua New Guinea", "PG", "Asia Pacific", "🇵🇬", "Proposed",
     "Social Media", 40, 40,
     "Growing Chinese investment while balancing Australia and the US",
     "Cybercrime Code Act 2016 with speech-restrictive provisions; no comprehensive DP law; periodic Facebook-restriction proposals.",
     "https://www.nicta.gov.pg/",
     [CM]),
    ("Fiji", "FJ", "Asia Pacific", "🇫🇯", "Effective",
     "Social Media", 40, 42,
     "Balancing China and traditional Western partners",
     "Online Safety Act 2018 (Online Safety Commission) plus data-protection provisions; genuine platform-content oversight.",
     "https://www.onlinesafety.org.fj/",
     [CM, UE]),
    ("Timor-Leste", "TL", "Asia Pacific", "🇹🇱", "Proposed",
     "Social Media", 32, 38,
     "Growing Chinese investment; broadly neutral",
     "Minimal platform-specific regulation; emerging data-protection discussions.",
     "https://www.anc.tl/",
     [DP]),

    # ---- Middle East remainder ----
    ("Iraq", "IQ", "Middle East", "🇮🇶", "Enforced",
     "Social Media; Direct Messaging", 56, 30,
     "Growing Chinese oil and infrastructure ties",
     "Periodic platform blocking and morality-driven content controls; draft cybercrime law; limited data-protection framework.",
     "https://www.cmc.iq/",
     [AR, CM]),
    ("Yemen", "YE", "Middle East", "🇾🇪", "Enforced",
     "Social Media; Direct Messaging", 54, 22,
     "Fragmented governance; some Chinese engagement",
     "Conflict-driven fragmentation with Houthi-area filtering and periodic shutdowns; no unified framework.",
     "https://freedomhouse.org/country/yemen/freedom-net",
     [AR, CM]),
    ("Syria", "SY", "Middle East", "🇸🇾", "Enforced",
     "Social Media; Direct Messaging", 58, 20,
     "Chinese reconstruction interest; broadly aligned",
     "Post-transition environment with legacy filtering and surveillance; content controls; no modern DP regime.",
     "https://freedomhouse.org/country/syria/freedom-net",
     [AR, CM]),

    # ---- Europe remainder ----
    ("Iceland", "IS", "Europe", "🇮🇸", "Effective",
     "Social Media; Streaming; App Store", 60, 38,
     "FTA with China (2013) but broadly aligned with EU/EEA caution",
     "GDPR applies via EEA; EU Digital Services Act being transposed via EEA, bringing platform risk and transparency duties.",
     "https://www.personuvernd.is/",
     [DP, CM, RA, TR, AI]),
    ("Serbia", "RS", "Europe", "🇷🇸", "Effective",
     "Social Media", 46, 25,
     "Strong Belt-and-Road / Huawei ties; steel-friendship; surveillance-camera deployments",
     "GDPR-aligned Data Protection Law (2018) enforced by the Commissioner; media-freedom concerns; no dedicated platform-safety law.",
     "https://www.poverenik.rs/",
     [DP, CM]),
    ("Albania", "AL", "Europe", "🇦🇱", "Effective",
     "Social Media; Streaming", 50, 45,
     "EU-accession orientation; China a minor factor",
     "GDPR-aligned DP law with 2024 amendments; a temporary TikTok ban in 2025 over minor-safety concerns raised platform scrutiny.",
     "https://www.idp.al/",
     [DP, CM, AA]),
    ("Bosnia and Herzegovina", "BA", "Europe", "🇧🇦", "Effective",
     "Social Media", 42, 40,
     "EU-accession orientation; some Chinese infrastructure loans",
     "Personal Data Protection Law with an active agency; EU-alignment reform underway; no dedicated platform-safety law.",
     "https://azlp.ba/",
     [DP]),
    ("Macedonia", "MK", "Europe", "🇲🇰", "Effective",
     "Social Media", 42, 42,
     "EU-accession orientation; limited China ties",
     "GDPR-aligned Personal Data Protection Law (2020); EU-alignment reforms; no dedicated platform-safety law.",
     "https://azlp.mk/",
     [DP]),
    ("Montenegro", "ME", "Europe", "🇲🇪", "Effective",
     "Social Media", 42, 38,
     "EU-accession orientation; a major China-financed highway raised debt concerns",
     "GDPR-aligned DP framework with EU-accession reforms; no dedicated platform-safety law.",
     "https://www.azlp.me/",
     [DP]),
    ("Moldova", "MD", "Europe", "🇲🇩", "Effective",
     "Social Media", 48, 40,
     "EU-accession orientation; China not a major factor",
     "GDPR-aligning DP law with reform in progress; active anti-disinformation and foreign-interference measures (Russia-facing).",
     "https://datepersonale.md/",
     [DP, CM, TR]),

    # ---- Latin America remainder ----
    ("Uruguay", "UY", "South America", "🇺🇾", "Enforced",
     "Social Media", 40, 40,
     "Largest trade partner; FTA talks; not restrictive",
     "Mature Data Protection & Habeas Data Law (EU adequacy, URCDP regulator); no platform-safety/age-assurance law.",
     "https://www.gub.uy/unidad-reguladora-control-datos-personales/",
     [DP]),
    ("Paraguay", "PY", "South America", "🇵🇾", "Passed",
     "Social Media", 38, 60,
     "One of the few Taiwan-recognizing states; cool relations with Beijing",
     "Comprehensive DP Law 7593/2025 (effective 2027) with enhanced child/adolescent protections; minimal platform regulation until then.",
     "https://www.dataguidance.com/news/paraguay-president-assents-data-protection-law",
     [DP, PC]),
    ("Bolivia", "BO", "South America", "🇧🇴", "Proposed",
     "Social Media", 34, 22,
     "Lithium and infrastructure partner; warming ties",
     "No comprehensive DP law (constitutional habeas-data only); DP bill under discussion; minimal platform regulation.",
     "https://www.att.gob.bo/",
     [DP]),
    ("Guyana", "GY", "South America", "🇬🇾", "Proposed",
     "Social Media", 34, 30,
     "Chinese infrastructure investment amid oil boom",
     "Data Protection Act 2023 passed; minimal platform-specific regulation.",
     "https://dpa.gov.gy/",
     [DP]),
    ("Suriname", "SR", "South America", "🇸🇷", "Proposed",
     "Social Media", 32, 20,
     "Significant Chinese community and investment ties",
     "Minimal platform-specific regulation; emerging data-protection discussions.",
     "https://gov.sr/",
     [DP]),
    ("Guatemala", "GT", "North America", "🇬🇹", "Proposed",
     "Social Media", 34, 58,
     "One of the last Taiwan-recognizing states; limited China ties",
     "No comprehensive DP law in force; DP bill under discussion; minimal platform regulation.",
     "https://www.sib.gob.gt/",
     [DP]),
    ("Panama", "PA", "North America", "🇵🇦", "Effective",
     "Social Media", 40, 55,
     "Left BRI in 2025 under US pressure; posture toward China cooled markedly",
     "DP Law 81/2019 (in force 2021, ANTAI regulator); constitutional privacy; no platform-safety/age-assurance law.",
     "https://www.antai.gob.pa/",
     [DP]),
    ("Honduras", "HN", "North America", "🇭🇳", "Proposed",
     "Social Media", 34, 30,
     "Switched recognition to Beijing in 2023; warming ties",
     "Constitutional habeas-data; no comprehensive DP law in force; minimal platform regulation.",
     "https://www.conatel.gob.hn/",
     [DP]),
    ("Nicaragua", "NI", "North America", "🇳🇮", "Enforced",
     "Social Media; Direct Messaging", 52, 18,
     "Switched recognition to Beijing in 2021; close alignment",
     "Special Cybercrime Law 2020 (speech-restrictive) plus 2022 personal-data law; state pressure on online expression.",
     "https://www.telcor.gob.ni/",
     [DP, CM, AR]),
    ("Jamaica", "JM", "North America", "🇯🇲", "Enforced",
     "Social Media", 42, 32,
     "Chinese infrastructure investment; broadly neutral",
     "Data Protection Act 2020 (in force with an Information Commissioner); no dedicated platform-safety law.",
     "https://www.oic.gov.jm/",
     [DP]),
    ("Trinidad and Tobago", "TT", "North America", "🇹🇹", "Effective",
     "Social Media", 40, 32,
     "Chinese infrastructure and energy ties; broadly neutral",
     "Data Protection Act (partially proclaimed) plus cybercrime provisions; limited platform-specific regulation.",
     "https://ttcsirt.gov.tt/",
     [DP]),
    ("Belize", "BZ", "North America", "🇧🇿", "Proposed",
     "Social Media", 30, 55,
     "One of the few Taiwan-recognizing states; limited China ties",
     "Minimal platform-specific regulation; nascent data-protection discussions.",
     "https://www.puc.bz/",
     [DP]),

    # ---- Micro-states / territories worth coloring ----
    ("Andorra", "AD", "Europe", "🇦🇩", "Effective",
     "Social Media", 44, 35,
     "EU-adjacent posture; limited China ties",
     "Data Protection Act (GDPR-adequate, APDA regulator); no dedicated platform-safety law.",
     "https://www.apda.ad/",
     [DP]),
    ("Liechtenstein", "LI", "Europe", "🇱🇮", "Effective",
     "Social Media; Streaming", 56, 35,
     "EEA-aligned; limited China ties",
     "GDPR applies via EEA; EU Digital Services Act transposed via EEA, bringing platform duties.",
     "https://www.datenschutzstelle.li/",
     [DP, CM, RA, TR]),
    ("Greenland", "GL", "North America", "🇬🇱", "Effective",
     "Social Media", 46, 32,
     "Strategic interest but restrictive posture toward Chinese investment",
     "Danish/EU data-protection framework applies; limited domestic platform-specific regulation.",
     "https://www.datatilsynet.dk/",
     [DP]),
]
